# Generated by Django 5.0.3 on 2024-05-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wynik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiek', models.IntegerField()),
                ('poczucie_smutku', models.IntegerField()),
                ('nerwowe_zachowanie', models.IntegerField()),
                ('problemy_ze_spaniem', models.IntegerField()),
                ('problemy_z_koncentracja', models.IntegerField()),
                ('przejadanie_sie', models.IntegerField()),
                ('poczucie_winy', models.IntegerField()),
                ('problem_z_przywiazaniem', models.IntegerField()),
                ('proba_samobojcza', models.FloatField()),
                ('wynik', models.IntegerField()),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
